---
title: "Untitled"
author: "hakmin"
date: '2019 12 10 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(leaflet)
mymap = leaflet() %>% addTiles()
crosstalk::bscols(
  mymap,
  mymap %>% setView(126.982, 37.5502, zoom=10)
)
```

```{r}
election  = geojsonio::geojson_read("predict_2020.json", what = "sp")
```

```{r}
poly1 = mymap %>% addPolygons(data=election,label=~당선)

# 지도에 색을 입히기 위해서 파레트 생성
pal = colorFactor(c("#0D7440", "#2A88C5",  "#C10D0D"), c("국민의당", "더불어민주당","새누리당"))

# 툴팁에 담을 정보 생성
labs = lapply(seq(nrow(election@data)), function(i) {
  paste0( '<p><b>', election@data[i, "선거구"]," : ",election@data[i, "읍면동명"], '</b></p><p>', 
          "<b>당선 : ", election@data[i, "당선"], '</b><p></p>', 
          "국민의당 : ", election@data[i, "국민의당"],'</p><p>', 
          "더불어민주당 : ", election@data[i, "더불어민주당"], '</p><p>',
          "새누리당 : ", election@data[i, "새누리당"], '</p>') 
})

# 선거구 경계 생성
election_gu = maptools::unionSpatialPolygons(election, election$선거구)

poly2 = leaflet(election) %>%
  addTiles %>%
  addPolygons(
    # 폴리곤 내부
    fillColor = ~pal(당선), fillOpacity = 0.5,
    # 폴리곤 경계
    weight = 1, opacity = 1, color = "white", dashArray=3,
    # 라벨
    label=lapply(labs, htmltools::HTML),
    # 하이라이트
    highlightOptions = highlightOptions(
      color = "#00ff00", opacity = 1, weight = 2, fillOpacity = 1,
      bringToFront = T, sendToBack = T))%>%
  addLegend(pal = pal, values = ~당선, opacity = 0.7, title = NULL, position = "bottomright") %>%
  addPolylines(
    data=election_gu,
    weight = 1.5,
    opacity = 1,
    color = "black")

crosstalk::bscols(poly1, poly2)
```

```{r}
library(crosstalk)
shared_elec = SharedData$new(election@data)
class(shared_elec)
```

```{r}
library(crosstalk)
library(plotly)

# election@data를 SharedData로 감싸 공유 데이터를 생성
shared_elec = SharedData$new(election@data, ~id)

p1 = plot_ly(shared_elec, x = ~소득, y = ~노령화지수, legendgroup=~당선) %>%
  add_markers(color=~당선, colors=c("#0D7440", "#2A88C5",  "#C10D0D"), opacity=0.6)

p2 = plot_ly(shared_elec, x = ~장애등급, y = ~사업체수, legendgroup=~당선) %>%
  add_markers(color=~당선, colors=c("#0D7440", "#2A88C5",  "#C10D0D"), opacity=0.6)

subplot(p1,p2) %>%
  layout(xaxis = list(title = "소득"),
         yaxis = list(title = "노령화지수"),
         xaxis2 = list(title = "장애인현황"),
         yaxis2 = list(title = "사업체수"),
         height=400, width=850) %>%
  highlight("plotly_selected")
```

```{r}
library(d3scatter)

shared_elec = SharedData$new(election)
shared_elec_df = SharedData$new(election@data, group=shared_elec$groupName())
shared_elec_dt = crosstalk::SharedData$new(election@data %>%
                 select(선거구,당선,읍면동명,소득,노령화지수), group=shared_elec$groupName())

DT::datatable(shared_elec_dt, width="100%")
```

```{r}
bscols(
  d3scatter(data=shared_elec_df, x=~소득,y=~노령화지수,color=~당선, height=300, width="100%"),
  d3scatter(data=shared_elec_df, x=~장애등급 ,y=~사업체수,color=~당선, height=300, width="100%")
)
```

```{r}
leaflet(shared_elec) %>%
  addProviderTiles("CartoDB.Positron") %>% 
  setView(126.982, 37.5502, zoom=10) %>%
  addPolygons(
    fillColor = ~pal(당선),
    weight = 1,
    opacity = 1,
    color = "white",
    dashArray=3,
    fillOpacity = 0.5,
    label = lapply(labs, htmltools::HTML)) %>%
  addLegend(pal = pal, values = ~당선, opacity = 0.7, title = NULL, position = "bottomright") %>%
  addPolylines(
    data=election_gu,
    weight = 1.5,
    opacity = 1,
    color = "black")
```

```{r}
bscols(
  list(filter_checkbox("당선", "당선", shared_elec_df, ~당선, inline=T),
       filter_slider("소득", "소득", shared_elec_df, ~소득, width="100%"),
       filter_select("동", "동", shared_elec_df, ~읍면동명)),
  d3scatter(shared_elec_df, ~소득, ~노령화지수, ~당선, width="100%", height=250),
  d3scatter(shared_elec_df, ~소득, ~노령화지수, ~당선, width="100%", height=250)
)
```