---
title: "Election"
author: "4dollar"
date: "2019년 12월 13일"
output:
  html_document: 
    toc: yes
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 모델링



## 시작-데이터프레임불러오기 
```{r read_csv_problems, warning=FALSE, message=FALSE}
# 인코딩 문제를 해결하는 두가지 방법
## 1 csv파일 인코딩을 ANSI로 저장
df1=read.csv('https://github.com/lhmlhm1111/Data_GongHak/raw/master/%EC%A0%84%EC%B2%98%EB%A6%AC/%EC%86%8C%EB%93%9D%EB%B0%98%EC%98%81%EC%B5%9C%EC%A2%85.csv',header=T, sep=',')

## 2 readAny 패키지 활용

library (devtools)

# 패키지를 로드합니다.
library(readAny)
df2= read.any('https://github.com/lhmlhm1111/Data_GongHak/raw/master/%EC%A0%84%EC%B2%98%EB%A6%AC/%EC%86%8C%EB%93%9D%EB%B0%98%EC%98%81%EC%B5%9C%EC%A2%85.csv', header=T, sep=',')


```

## 데이터프레임 선형모델, 분산 분석, 각 독립변수 유의수준 유의성 검정

```{r F-test, warning=FALSE, message=FALSE}
attach (df1)
names (df1)
options("scipen" = 100)

model3 <- aov(새누리당~독거노인수+유년부양비+노년부양비+노령화지수+사업체수+종사자수+사업체.창업률+기초수급자인원수+보육시설+금융기관+사업체.평균연령+인구+면적+인구밀도+ 소득)
summary(model3)
  model4 <-lm(새누리당~독거노인수+유년부양비+노년부양비+노령화지수+사업체수+종사자수+사업체.창업률+기초수급자인원수+보육시설+금융기관+사업체.평균연령+인구+면적+인구밀도+ 소득)
summary(model4)
```
 
## 변수 중요도 파악, 변수선택 
```{r multivariate selection 1, warning=FALSE, message=FALSE}

library(reticulate)

matplotlib <- import("matplotlib")
matplotlib$use("Agg", force = TRUE)
```


```{python multivariate selection2} 

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
#원본 데이터 호출 (깃허브에 저장된 데이터 파일 호출)
df4 = pd.read_csv('https://github.com/lhmlhm1111/Data_GongHak/raw/master/11-22totaldata.txt', encoding='utf-8', sep=',')

#train, test 데이터 생성
X, y = df4.iloc[:,8:], df4.iloc[:,4]


import warnings
warnings.filterwarnings("ignore")

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=0)


## 랜덤포레스트 회귀 모델 생성&적용
rf = RandomForestRegressor()

rf.fit(X_train,y_train)

predicted = rf.predict(X_test)
rf.feature_importances_
['{:f}'.format(x) for x in rf.feature_importances_]

```

 + 상호관계 다중공선성

 
```{python multicollinearity}
import PyQt5
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
#가공할 데이터 호출
data = pd.read_csv('https://github.com/lhmlhm1111/Data_GongHak/raw/master/11-22totaldata.txt',encoding='UTF-8',sep=',')

#데이터 가공 : 변수 선별 (제외할 변수)
df3 = data.drop(['year','읍면동명','자치구','선거인수','인구'],axis=1)
#상관계수 분포 지도 (Heat Map) 작성
plt.rc('font', family='Malgun gothic')

fig = plt.figure(figsize=[20,20])

ax=sns.heatmap(df3.corr(),annot=True,square=True)
plt.title('변수 간 상관관계')
plt.show()
```

최종적으로 소득 , 인구밀도 , 사업체수 , 장애등급별 장애인현황 ,독거노인수 , 노령화지수 선택

## 모델 선택 및 적용

[모델 선택과정](https://github.com/lhmlhm1111/Data_GongHak/blob/master/%EC%97%AC%EB%9F%AC%EA%B0%80%EC%A7%80_%EB%AA%A8%EB%8D%B8_%EB%8F%8C%EB%A0%A4%EB%B3%B8_%EA%B2%B0%EA%B3%BC.ipynb)


[최신 자료 예측 결과](https://github.com/lhmlhm1111/Data_GongHak/blob/master/%EB%AA%A8%EB%8D%B8/final_%EC%B5%9C%EC%A2%85_%EC%83%88%EB%88%84%EB%A6%AC%EB%8B%B9%2B%EB%8D%94%EB%B6%88%EC%96%B4%EB%AF%BC%EC%A3%BC%EB%8B%B9.ipynb)

# 결론

## 시각화

[시각화](https://dsrla123.github.io/data_engineering/product.html)

## 한계&제언 - 앞으로 
 변수변환, hyperparameter tuning 등의 미흡함.관측점 자체의 독립성?
 앞으로 다음 학기 경선 후 후보자 발표되면 후보자의 관한 요인, 시국 여론 정보 (krvote 웹 크롤링부분 참고)추가, 그 이후 지역구 코드 활용해서 서울 이외의 지역까지 확장 가능?
```{python 1:1 relation example}
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt
df1 = pd.read_csv('https://github.com/lhmlhm1111/Data_GongHak/raw/master/%EB%AA%A8%EB%8D%B8/12%2C16%EB%85%84%EB%8F%84_Training_Data_set_1.csv',encoding='UTF-8',sep=',')
x = '소득(동별)'
k=15
for i in range(k):
    df1.loc[(df1[x] >= (df1[x].max()-df1[x].min())/k*i ) & (df1[x] <= (df1[x].max()-df1[x].min())/k*(i+1) ) ,x] = i+1

plt.rc('font', family='Malgun Gothic')
fig = plt.figure(figsize=[16,16])
ax1 = fig.add_subplot(1,1,1)
ax1 = sns.barplot(x,y='새누리당',data=df1.groupby(x)['새누리당'].mean().reset_index())
plt.title('소득-새누리득표수')
plt.show()
```

# 질의
 

